//! File walk (Idea §3, §5; task 2.1).
//!
//! Built on the `ignore` crate (ripgrep's engine). CF owns the *universe* of
//! files — the `[scan]` settings are the authoritative `cf_scope`; a provider
//! may later only veto *within* it, never widen it (`provider_filter(cf_scope)`,
//! Idea §5). The walk:
//!
//! * respects `.gitignore` / `.ignore` (with an opt-out),
//! * applies `[scan] extra_ignores` as additional authoritative exclusions,
//! * keeps only files of the configured languages (by extension, or a shell
//!   script identified by its shebang),
//! * drops generated / minified files via a header sniff so their pseudo-
//!   comments never pollute results, and
//! * returns files in a deterministic (sorted) order for reproducibility.

use std::fs::File;
use std::io::{BufRead, BufReader, Read};
use std::path::{Path, PathBuf};

use ignore::overrides::OverrideBuilder;
use ignore::WalkBuilder;

use cf_core::config::ScanConfig;
use cf_core::error::{CfError, CfResult};
use cf_core::lang::Language;

/// Bytes of a file header sniffed for the generated-file heuristic.
const GENERATED_SNIFF_BYTES: u64 = 8 * 1024;

/// A first line longer than this (no break) is treated as minified → generated.
const MINIFIED_FIRST_LINE_BYTES: usize = 2_000;

/// Case-insensitive markers that flag a file as generated (Idea §3).
const GENERATED_MARKERS: [&str; 6] = [
    "@generated",
    "do not edit",
    "code generated",
    "auto-generated",
    "autogenerated",
    "generated by",
];

/// What the walk should collect.
#[derive(Debug, Clone)]
pub struct WalkOptions {
    /// Honor `.gitignore` / `.ignore` (and parent ignores).
    pub respect_gitignore: bool,
    /// Languages to keep.
    pub languages: Vec<Language>,
    /// Authoritative extra exclusion globs (gitignore syntax).
    pub extra_ignores: Vec<String>,
    /// Drop generated / minified files via the header sniff.
    pub skip_generated: bool,
}

impl WalkOptions {
    /// Derives walk options from the resolved `[scan]` config (Idea §12).
    #[must_use]
    pub fn from_scan_config(scan: &ScanConfig) -> Self {
        Self {
            respect_gitignore: scan.respect_gitignore,
            languages: scan.languages.clone(),
            extra_ignores: scan.extra_ignores.clone(),
            skip_generated: true,
        }
    }
}

/// One source file selected by the walk.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct WalkedFile {
    /// Absolute path on disk (for reading).
    pub path: PathBuf,
    /// The detected language.
    pub language: Language,
}

/// Walks `root`, returning the in-scope source files in sorted order.
///
/// # Errors
/// Returns [`CfError::Walk`] if an `extra_ignores` glob is invalid or the
/// override set cannot be built. Individual unreadable directory entries are
/// skipped (traversal robustness), not fatal.
pub fn walk(root: &Path, options: &WalkOptions) -> CfResult<Vec<WalkedFile>> {
    let overrides = build_overrides(root, &options.extra_ignores)?;

    let mut builder = WalkBuilder::new(root);
    configure(&mut builder, options);
    builder.overrides(overrides);

    let mut files = Vec::new();
    for entry in builder.build() {
        // Skip entries the walker could not stat (broken symlink, permissions);
        // a per-entry hiccup must not abort the scan (Idea §6 robustness).
        let Ok(entry) = entry else {
            continue;
        };
        if !entry.file_type().is_some_and(|t| t.is_file()) {
            continue;
        }
        let path = entry.path();
        let Some(language) = language_for_path(path, &options.languages) else {
            continue;
        };
        if options.skip_generated && is_generated(path) {
            continue;
        }
        files.push(WalkedFile {
            path: path.to_path_buf(),
            language,
        });
    }

    // Deterministic order — load-bearing for reproducible reports (Idea §11).
    files.sort();
    Ok(files)
}

/// Normalizes a path to a `/`-separated repo-relative string (Idea §11).
#[must_use]
pub fn to_repo_relative(path: &Path, root: &Path) -> String {
    let relative = path.strip_prefix(root).unwrap_or(path);
    relative.to_string_lossy().replace('\\', "/")
}

/// Applies the ignore-source toggles for the chosen mode.
fn configure(builder: &mut WalkBuilder, options: &WalkOptions) {
    let respect = options.respect_gitignore;
    builder
        .git_ignore(respect)
        .git_global(respect)
        .git_exclude(respect)
        .ignore(respect)
        .parents(respect)
        // Honor `.gitignore` even outside a git repo (so fixtures behave), and
        // skip hidden files unless we are explicitly scanning everything.
        .require_git(false)
        .hidden(respect);
}

/// Builds the override set that applies `extra_ignores` as exclusions.
fn build_overrides(root: &Path, extra_ignores: &[String]) -> CfResult<ignore::overrides::Override> {
    let mut builder = OverrideBuilder::new(root);
    for glob in extra_ignores {
        let pattern = to_exclusion_glob(glob);
        builder.add(&pattern).map_err(|e| {
            CfError::walk(format!("invalid extra_ignore glob {glob:?}")).caused_by(e)
        })?;
    }
    builder
        .build()
        .map_err(|e| CfError::walk("building ignore overrides").caused_by(e))
}

/// Converts an ignore glob into an `ignore`-override exclusion (`!`-prefixed),
/// expanding a trailing `/` to match directory contents.
fn to_exclusion_glob(glob: &str) -> String {
    let trimmed = glob.trim();
    let body = match trimmed.strip_suffix('/') {
        Some(dir) => format!("{dir}/**"),
        None => trimmed.to_owned(),
    };
    format!("!{body}")
}

/// Determines the language of a file, by extension or shell shebang, filtered to
/// the enabled set.
fn language_for_path(path: &Path, enabled: &[Language]) -> Option<Language> {
    if let Some(extension) = path.extension().and_then(|e| e.to_str()) {
        if let Some(language) = language_from_extension(extension) {
            return enabled.contains(&language).then_some(language);
        }
    }
    // An extensionless file may still be a shell script (by shebang).
    if enabled.contains(&Language::Shell) && has_shell_shebang(path) {
        return Some(Language::Shell);
    }
    None
}

/// Maps a file extension to a language (Idea §3 committed set).
fn language_from_extension(extension: &str) -> Option<Language> {
    match extension.to_ascii_lowercase().as_str() {
        "py" | "pyi" => Some(Language::Python),
        "ts" | "mts" | "cts" | "tsx" => Some(Language::TypeScript),
        "js" | "mjs" | "cjs" | "jsx" => Some(Language::JavaScript),
        "sh" | "bash" => Some(Language::Shell),
        _ => None,
    }
}

/// Whether the file's first line is a shell shebang.
fn has_shell_shebang(path: &Path) -> bool {
    let Ok(file) = File::open(path) else {
        return false;
    };
    let mut first_line = String::new();
    if BufReader::new(file).read_line(&mut first_line).is_err() {
        return false;
    }
    let line = first_line.trim_start();
    // "sh" as a substring covers sh / bash / dash / zsh / ash interpreters.
    line.starts_with("#!") && line.contains("sh")
}

/// Whether a file looks generated or minified (Idea §3 header sniff).
fn is_generated(path: &Path) -> bool {
    let Ok(header) = read_header(path, GENERATED_SNIFF_BYTES) else {
        return false;
    };
    let text = String::from_utf8_lossy(&header);
    let lowered = text.to_ascii_lowercase();
    if GENERATED_MARKERS
        .iter()
        .any(|marker| lowered.contains(marker))
    {
        return true;
    }
    // Minified: the whole file on one very long line.
    let first_line_len = text.split('\n').next().map_or(0, str::len);
    first_line_len > MINIFIED_FIRST_LINE_BYTES
}

/// Reads up to `max` bytes of a file's head.
fn read_header(path: &Path, max: u64) -> std::io::Result<Vec<u8>> {
    let mut buffer = Vec::new();
    File::open(path)?.take(max).read_to_end(&mut buffer)?;
    Ok(buffer)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn opts(languages: &[Language]) -> WalkOptions {
        WalkOptions {
            respect_gitignore: true,
            languages: languages.to_vec(),
            extra_ignores: Vec::new(),
            skip_generated: true,
        }
    }

    fn names(files: &[WalkedFile], root: &Path) -> Vec<String> {
        files
            .iter()
            .map(|f| to_repo_relative(&f.path, root))
            .collect()
    }

    #[test]
    fn test_selects_source_files_by_language() {
        let tmp = TempDir::new().unwrap();
        for (name, body) in [
            ("a.py", "# c"),
            ("b.ts", "// c"),
            ("c.js", "// c"),
            ("d.sh", "#!/bin/sh"),
            ("readme.md", "# title"),
            ("conf.toml", "x = 1"),
        ] {
            fs::write(tmp.path().join(name), body).unwrap();
        }
        let files = walk(tmp.path(), &opts(&Language::ALL)).unwrap();
        assert_eq!(
            names(&files, tmp.path()),
            vec!["a.py", "b.ts", "c.js", "d.sh"]
        );
    }

    #[test]
    fn test_language_filter_excludes_disabled() {
        let tmp = TempDir::new().unwrap();
        fs::write(tmp.path().join("a.py"), "# c").unwrap();
        fs::write(tmp.path().join("b.ts"), "// c").unwrap();
        let files = walk(tmp.path(), &opts(&[Language::Python])).unwrap();
        assert_eq!(names(&files, tmp.path()), vec!["a.py"]);
    }

    #[test]
    fn test_respects_and_opts_out_of_gitignore() {
        let tmp = TempDir::new().unwrap();
        fs::write(tmp.path().join(".gitignore"), "ignored/\n").unwrap();
        fs::create_dir(tmp.path().join("ignored")).unwrap();
        fs::write(tmp.path().join("ignored/x.py"), "# c").unwrap();
        fs::write(tmp.path().join("kept.py"), "# c").unwrap();

        let respected = walk(tmp.path(), &opts(&[Language::Python])).unwrap();
        assert_eq!(names(&respected, tmp.path()), vec!["kept.py"]);

        let mut all = opts(&[Language::Python]);
        all.respect_gitignore = false;
        let scanned = walk(tmp.path(), &all).unwrap();
        assert_eq!(names(&scanned, tmp.path()), vec!["ignored/x.py", "kept.py"]);
    }

    #[test]
    fn test_extra_ignores_are_authoritative() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir(tmp.path().join("vendor")).unwrap();
        fs::write(tmp.path().join("vendor/lib.py"), "# c").unwrap();
        fs::write(tmp.path().join("main.py"), "# c").unwrap();
        fs::write(tmp.path().join("x.generated.py"), "# c").unwrap();

        let mut o = opts(&[Language::Python]);
        o.extra_ignores = vec!["vendor/".to_owned(), "*.generated.*".to_owned()];
        let files = walk(tmp.path(), &o).unwrap();
        assert_eq!(names(&files, tmp.path()), vec!["main.py"]);
    }

    #[test]
    fn test_generated_file_skipped() {
        let tmp = TempDir::new().unwrap();
        fs::write(tmp.path().join("gen.py"), "# @generated by tool\nx = 1\n").unwrap();
        fs::write(tmp.path().join("hand.py"), "# written by a human\n").unwrap();
        let files = walk(tmp.path(), &opts(&[Language::Python])).unwrap();
        assert_eq!(names(&files, tmp.path()), vec!["hand.py"]);
    }

    #[test]
    fn test_minified_file_skipped() {
        let tmp = TempDir::new().unwrap();
        let long_line = format!("var x={};", "0".repeat(MINIFIED_FIRST_LINE_BYTES + 10));
        fs::write(tmp.path().join("min.js"), long_line).unwrap();
        fs::write(tmp.path().join("ok.js"), "// short\nvar y = 1;\n").unwrap();
        let files = walk(tmp.path(), &opts(&[Language::JavaScript])).unwrap();
        assert_eq!(names(&files, tmp.path()), vec!["ok.js"]);
    }

    #[test]
    fn test_shell_detected_by_shebang_without_extension() {
        let tmp = TempDir::new().unwrap();
        fs::write(tmp.path().join("runme"), "#!/usr/bin/env bash\necho hi\n").unwrap();
        fs::write(tmp.path().join("notes"), "just text, no shebang\n").unwrap();
        let files = walk(tmp.path(), &opts(&[Language::Shell])).unwrap();
        assert_eq!(names(&files, tmp.path()), vec!["runme"]);
    }
}
